### ISSUE TITLE
Error @types/lodash when try to build the project

### ISSUE THREAD

**Issue by gabrielseco** [CachopoTeam/genmite#4]
Error when trying to build the project with @types/lodash it says 

node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'

The workaround by now is removing this package from node_modules

**Comment by gabrielseco** [comment]
It seems it's a bug related with https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375

When they fix it, we'll have the solution updating the lodash package

**Comment by aj-r** [comment]
Looks like this has been fixed in the latest version of lodash (4.14.103). Try running `npm install -S @types/lodash@latest` (or similar in yarn) with TS 2.7, and see if that fixes it.

**Comment by gabrielseco** [comment]
Thanks for the feedback @aj-r. I'll take a look and see how it goes

**Comment by gabrielseco** [comment]
I tried today and it works correctly, thanks @aj-r
